<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1, 'custom_id'     => getUniqueString('countries'), 'code' => 'AF',  'phonecode' => 93 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 2, 'custom_id'     => getUniqueString('countries'), 'code' => 'AL',  'phonecode' => 355 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 3, 'custom_id'     => getUniqueString('countries'), 'code' => 'DZ', 'phonecode' => 213 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 4, 'custom_id'     => getUniqueString('countries'), 'code' => 'AS', 'phonecode' => 1684 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 5, 'custom_id'     => getUniqueString('countries'), 'code' => 'AD', 'phonecode' => 376 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 6, 'custom_id'     => getUniqueString('countries'), 'code' => 'AO', 'phonecode' => 244 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 7, 'custom_id'     => getUniqueString('countries'), 'code' => 'AI', illa'phonecode' => 1264 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 8, 'custom_id'     => getUniqueString('countries'), 'code' => 'AQ', rctica'phonecode' => 0 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 9, 'custom_id'     => getUniqueString('countries'), 'code' => 'AG', 'phonecode' => 1268 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 10, 'custom_id'     => getUniqueString('countries'), 'code' => 'AR', 'phonecode' => 54 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 11, 'custom_id'     => getUniqueString('countries'), 'code' => 'AM', 'phonecode' => 374 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 12, 'custom_id'     => getUniqueString('countries'), 'code' => 'AW', 'phonecode' => 297 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 13, 'custom_id'     => getUniqueString('countries'), 'code' => 'AU', 'phonecode' => 61 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 14, 'custom_id'     => getUniqueString('countries'), 'code' => 'AT', 'phonecode' => 43 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 15, 'custom_id'     => getUniqueString('countries'), 'code' => 'AZ', 'phonecode' => 994 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 16, 'custom_id'     => getUniqueString('countries'), 'code' => 'BS', 'phonecode' => 1242 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 17, 'custom_id'     => getUniqueString('countries'), 'code' => 'BH', 'phonecode' => 973 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 18, 'custom_id'     => getUniqueString('countries'), 'code' => 'BD', 'phonecode' => 880 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 19, 'custom_id'     => getUniqueString('countries'), 'code' => 'BB', 'phonecode' => 1246 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 20, 'custom_id'     => getUniqueString('countries'), 'code' => 'BY', 'phonecode' => 375 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 21, 'custom_id'     => getUniqueString('countries'), 'code' => 'BE', 'phonecode' => 32 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 22, 'custom_id'     => getUniqueString('countries'), 'code' => 'BZ', 'phonecode' => 501 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 23, 'custom_id'     => getUniqueString('countries'), 'code' => 'BJ', 'phonecode' => 229 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 24, 'custom_id'     => getUniqueString('countries'), 'code' => 'BM', 'phonecode' => 1441 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 25, 'custom_id'     => getUniqueString('countries'), 'code' => 'BT', 'phonecode' => 975 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 26, 'custom_id'     => getUniqueString('countries'), 'code' => 'BO', 'phonecode' => 591 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 27, 'custom_id'     => getUniqueString('countries'), 'code' => 'BA', 'phonecode' => 387 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 28, 'custom_id'     => getUniqueString('countries'), 'code' => 'BW', 'phonecode' => 267 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 29, 'custom_id'     => getUniqueString('countries'), 'code' => 'BV', 'phonecode' => 0 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 30, 'custom_id'     => getUniqueString('countries'), 'code' => 'BR', 'phonecode' => 55 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 31, 'custom_id'     => getUniqueString('countries'), 'code' => 'IO', 'phonecode' => 246 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 32, 'custom_id'     => getUniqueString('countries'), 'code' => 'BN', 'phonecode' => 673 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 33, 'custom_id'     => getUniqueString('countries'), 'code' => 'BG', 'phonecode' => 359 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 34, 'custom_id'     => getUniqueString('countries'), 'code' => 'BF', 'phonecode' => 226 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 35, 'custom_id'     => getUniqueString('countries'), 'code' => 'BI', 'phonecode' => 257 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 36, 'custom_id'     => getUniqueString('countries'), 'code' => 'KH', 'phonecode' => 855 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 37, 'custom_id'     => getUniqueString('countries'), 'code' => 'CM', 'phonecode' => 237 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 38, 'custom_id'     => getUniqueString('countries'), 'code' => 'CA', 'phonecode' => 1 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 39, 'custom_id'     => getUniqueString('countries'), 'code' => 'CV',  'phonecode' => 238 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 40, 'custom_id'     => getUniqueString('countries'), 'code' => 'KY', 'phonecode' => 1345 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 41, 'custom_id'     => getUniqueString('countries'), 'code' => 'CF', 'phonecode' => 236 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 42, 'custom_id'     => getUniqueString('countries'), 'code' => 'TD', 'phonecode' => 235 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 43, 'custom_id'     => getUniqueString('countries'), 'code' => 'CL', 'phonecode' => 56 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 44, 'custom_id'     => getUniqueString('countries'), 'code' => 'CN', 'phonecode' => 86 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 45, 'custom_id'     => getUniqueString('countries'), 'code' => 'CX', 'phonecode' => 61 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 46, 'custom_id'     => getUniqueString('countries'), 'code' => 'CC', 'phonecode' => 672 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 47, 'custom_id'     => getUniqueString('countries'), 'code' => 'CO', 'phonecode' => 57 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 48, 'custom_id'     => getUniqueString('countries'), 'code' => 'KM', 'phonecode' => 269 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 49, 'custom_id'     => getUniqueString('countries'), 'code' => 'CG', 'phonecode' => 242 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 50, 'custom_id'     => getUniqueString('countries'), 'code' => 'CD', 'phonecode' => 242 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 51, 'custom_id'     => getUniqueString('countries'), 'code' => 'CK',  'phonecode' => 682 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 52, 'custom_id'     => getUniqueString('countries'), 'code' => 'CR', 'phonecode' => 506 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 53, 'custom_id'     => getUniqueString('countries'), 'code' => 'CI',  'phonecode' => 225 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 54, 'custom_id'     => getUniqueString('countries'), 'code' => 'HR', 'phonecode' => 385 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 55, 'custom_id'     => getUniqueString('countries'), 'code' => 'CU', 'phonecode' => 53 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 56, 'custom_id'     => getUniqueString('countries'), 'code' => 'CY', 'phonecode' => 357 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 57, 'custom_id'     => getUniqueString('countries'), 'code' => 'CZ', 'phonecode' => 420 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 58, 'custom_id'     => getUniqueString('countries'), 'code' => 'DK', 'phonecode' => 45 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 59, 'custom_id'     => getUniqueString('countries'), 'code' => 'DJ', 'phonecode' => 253 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 60, 'custom_id'     => getUniqueString('countries'), 'code' => 'DM', 'phonecode' => 1767 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 61, 'custom_id'     => getUniqueString('countries'), 'code' => 'DO', 'phonecode' => 1809 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 62, 'custom_id'     => getUniqueString('countries'), 'code' => 'TP', 'phonecode' => 670 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 63, 'custom_id'     => getUniqueString('countries'), 'code' => 'EC', 'phonecode' => 593 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 64, 'custom_id'     => getUniqueString('countries'), 'code' => 'EG', 'phonecode' => 20 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 65, 'custom_id'     => getUniqueString('countries'), 'code' => 'SV', 'phonecode' => 503 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 66, 'custom_id'     => getUniqueString('countries'), 'code' => 'GQ', 'phonecode' => 240 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 67, 'custom_id'     => getUniqueString('countries'), 'code' => 'ER', 'phonecode' => 291 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 68, 'custom_id'     => getUniqueString('countries'), 'code' => 'EE', 'phonecode' => 372 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 69, 'custom_id'     => getUniqueString('countries'), 'code' => 'ET', 'phonecode' => 251 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 70, 'custom_id'     => getUniqueString('countries'), 'code' => 'XA', 'phonecode' => 61 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 71, 'custom_id'     => getUniqueString('countries'), 'code' => 'FK', 'phonecode' => 500 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 72, 'custom_id'     => getUniqueString('countries'), 'code' => 'FO', 'phonecode' => 298 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 73, 'custom_id'     => getUniqueString('countries'), 'code' => 'FJ', 'phonecode' => 679 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 74, 'custom_id'     => getUniqueString('countries'), 'code' => 'FI', 'phonecode' => 358 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 75, 'custom_id'     => getUniqueString('countries'), 'code' => 'FR', 'phonecode' => 33 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 76, 'custom_id'     => getUniqueString('countries'), 'code' => 'GF', 'phonecode' => 594 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 77, 'custom_id'     => getUniqueString('countries'), 'code' => 'PF', 'phonecode' => 689 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 78, 'custom_id'     => getUniqueString('countries'), 'code' => 'TF', 'phonecode' => 0 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 79, 'custom_id'     => getUniqueString('countries'), 'code' => 'GA', 'phonecode' => 241 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 80, 'custom_id'     => getUniqueString('countries'), 'code' => 'GM', 'phonecode' => 220 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 81, 'custom_id'     => getUniqueString('countries'), 'code' => 'GE', 'phonecode' => 995 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 82, 'custom_id'     => getUniqueString('countries'), 'code' => 'DE', 'phonecode' => 49 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 83, 'custom_id'     => getUniqueString('countries'), 'code' => 'GH', 'phonecode' => 233 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 84, 'custom_id'     => getUniqueString('countries'), 'code' => 'GI', 'phonecode' => 350 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 85, 'custom_id'     => getUniqueString('countries'), 'code' => 'GR', 'phonecode' => 30 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 86, 'custom_id'     => getUniqueString('countries'), 'code' => 'GL', 'phonecode' => 299 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 87, 'custom_id'     => getUniqueString('countries'), 'code' => 'GD', 'phonecode' => 1473 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 88, 'custom_id'     => getUniqueString('countries'), 'code' => 'GP', 'phonecode' => 590 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 89, 'custom_id'     => getUniqueString('countries'), 'code' => 'GU', 'phonecode' => 1671 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 90, 'custom_id'     => getUniqueString('countries'), 'code' => 'GT', 'phonecode' => 502 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 91, 'custom_id'     => getUniqueString('countries'), 'code' => 'XU', 'phonecode' => 44 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 92, 'custom_id'     => getUniqueString('countries'), 'code' => 'GN', 'phonecode' => 224 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 93, 'custom_id'     => getUniqueString('countries'), 'code' => 'GW', 'phonecode' => 245 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 94, 'custom_id'     => getUniqueString('countries'), 'code' => 'GY', 'phonecode' => 592 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 95, 'custom_id'     => getUniqueString('countries'), 'code' => 'HT', 'phonecode' => 509 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 96, 'custom_id'     => getUniqueString('countries'), 'code' => 'HM','phonecode' => 0 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 97, 'custom_id'     => getUniqueString('countries'), 'code' => 'HN', 'phonecode' => 504 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 98, 'custom_id'     => getUniqueString('countries'), 'code' => 'HK', 'phonecode' => 852 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 99, 'custom_id'     => getUniqueString('countries'), 'code' => 'HU', 'phonecode' => 36 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 100, 'custom_id'     => getUniqueString('countries'), 'code' => 'IS', 'phonecode' => 354 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 101, 'custom_id'     => getUniqueString('countries'), 'code' => 'IN', 'phonecode' => 91 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 102, 'custom_id'     => getUniqueString('countries'), 'code' => 'ID', 'phonecode' => 62 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 103, 'custom_id'     => getUniqueString('countries'), 'code' => 'IR', 'phonecode' => 98 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 104, 'custom_id'     => getUniqueString('countries'), 'code' => 'IQ', 'phonecode' => 964 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 105, 'custom_id'     => getUniqueString('countries'), 'code' => 'IE', 'phonecode' => 353 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 106, 'custom_id'     => getUniqueString('countries'), 'code' => 'IL', 'phonecode' => 972 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 107, 'custom_id'     => getUniqueString('countries'), 'code' => 'IT', 'phonecode' => 39 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 108, 'custom_id'     => getUniqueString('countries'), 'code' => 'JM', 'phonecode' => 1876 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 109, 'custom_id'     => getUniqueString('countries'), 'code' => 'JP', 'phonecode' => 81 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 110, 'custom_id'     => getUniqueString('countries'), 'code' => 'XJ', 'phonecode' => 44 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 111, 'custom_id'     => getUniqueString('countries'), 'code' => 'JO', 'phonecode' => 962 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 112, 'custom_id'     => getUniqueString('countries'), 'code' => 'KZ', 'phonecode' => 7 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 113, 'custom_id'     => getUniqueString('countries'), 'code' => 'KE', 'phonecode' => 254 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 114, 'custom_id'     => getUniqueString('countries'), 'code' => 'KI', 'phonecode' => 686 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 115, 'custom_id'     => getUniqueString('countries'), 'code' => 'KP', 'phonecode' => 850 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 116, 'custom_id'     => getUniqueString('countries'), 'code' => 'KR', 'phonecode' => 82 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 117, 'custom_id'     => getUniqueString('countries'), 'code' => 'KW', 'phonecode' => 965 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 118, 'custom_id'     => getUniqueString('countries'), 'code' => 'KG', 'phonecode' => 996 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 119, 'custom_id'     => getUniqueString('countries'), 'code' => 'LA', 'phonecode' => 856 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 120, 'custom_id'     => getUniqueString('countries'), 'code' => 'LV', 'phonecode' => 371 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 121, 'custom_id'     => getUniqueString('countries'), 'code' => 'LB', 'phonecode' => 961 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 122, 'custom_id'     => getUniqueString('countries'), 'code' => 'LS', 'phonecode' => 266 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 123, 'custom_id'     => getUniqueString('countries'), 'code' => 'LR', 'phonecode' => 231 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 124, 'custom_id'     => getUniqueString('countries'), 'code' => 'LY', 'phonecode' => 218 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 125, 'custom_id'     => getUniqueString('countries'), 'code' => 'LI', 'phonecode' => 423 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 126, 'custom_id'     => getUniqueString('countries'), 'code' => 'LT', 'phonecode' => 370 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 127, 'custom_id'     => getUniqueString('countries'), 'code' => 'LU', 'phonecode' => 352 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 128, 'custom_id'     => getUniqueString('countries'), 'code' => 'MO', 'phonecode' => 853 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 129, 'custom_id'     => getUniqueString('countries'), 'code' => 'MK', 'phonecode' => 389 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 130, 'custom_id'     => getUniqueString('countries'), 'code' => 'MG', 'phonecode' => 261 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 131, 'custom_id'     => getUniqueString('countries'), 'code' => 'MW', 'phonecode' => 265 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 132, 'custom_id'     => getUniqueString('countries'), 'code' => 'MY', 'phonecode' => 60 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 133, 'custom_id'     => getUniqueString('countries'), 'code' => 'MV', 'phonecode' => 960 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 134, 'custom_id'     => getUniqueString('countries'), 'code' => 'ML', 'phonecode' => 223 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 135, 'custom_id'     => getUniqueString('countries'), 'code' => 'MT', 'phonecode' => 356 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 136, 'custom_id'     => getUniqueString('countries'), 'code' => 'XM', 'phonecode' => 44 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 137, 'custom_id'     => getUniqueString('countries'), 'code' => 'MH', 'phonecode' => 692 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 138, 'custom_id'     => getUniqueString('countries'), 'code' => 'MQ', 'phonecode' => 596 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 139, 'custom_id'     => getUniqueString('countries'), 'code' => 'MR', 'phonecode' => 222 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 140, 'custom_id'     => getUniqueString('countries'), 'code' => 'MU', 'phonecode' => 230 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 141, 'custom_id'     => getUniqueString('countries'), 'code' => 'YT', 'phonecode' => 269 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 142, 'custom_id'     => getUniqueString('countries'), 'code' => 'MX', 'phonecode' => 52 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 143, 'custom_id'     => getUniqueString('countries'), 'code' => 'FM', 'phonecode' => 691 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 144, 'custom_id'     => getUniqueString('countries'), 'code' => 'MD', 'phonecode' => 373 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 145, 'custom_id'     => getUniqueString('countries'), 'code' => 'MC', 'phonecode' => 377 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 146, 'custom_id'     => getUniqueString('countries'), 'code' => 'MN', 'phonecode' => 976 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 147, 'custom_id'     => getUniqueString('countries'), 'code' => 'MS', 'phonecode' => 1664 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 148, 'custom_id'     => getUniqueString('countries'), 'code' => 'MA', 'phonecode' => 212 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 149, 'custom_id'     => getUniqueString('countries'), 'code' => 'MZ', 'phonecode' => 258 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 150, 'custom_id'     => getUniqueString('countries'), 'code' => 'MM', 'phonecode' => 95 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 151, 'custom_id'     => getUniqueString('countries'), 'code' => 'NA', 'phonecode' => 264 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 152, 'custom_id'     => getUniqueString('countries'), 'code' => 'NR', 'phonecode' => 674 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 153, 'custom_id'     => getUniqueString('countries'), 'code' => 'NP', 'phonecode' => 977 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 154, 'custom_id'     => getUniqueString('countries'), 'code' => 'AN', 'phonecode' => 599 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 155, 'custom_id'     => getUniqueString('countries'), 'code' => 'NL', 'phonecode' => 31 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 156, 'custom_id'     => getUniqueString('countries'), 'code' => 'NC', 'phonecode' => 687 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 157, 'custom_id'     => getUniqueString('countries'), 'code' => 'NZ', 'phonecode' => 64 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 158, 'custom_id'     => getUniqueString('countries'), 'code' => 'NI', 'phonecode' => 505 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 159, 'custom_id'     => getUniqueString('countries'), 'code' => 'NE', 'phonecode' => 227 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 160, 'custom_id'     => getUniqueString('countries'), 'code' => 'NG', 'phonecode' => 234 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 161, 'custom_id'     => getUniqueString('countries'), 'code' => 'NU', 'phonecode' => 683 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 162, 'custom_id'     => getUniqueString('countries'), 'code' => 'NF', 'phonecode' => 672 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 163, 'custom_id'     => getUniqueString('countries'), 'code' => 'MP', 'phonecode' => 1670 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 164, 'custom_id'     => getUniqueString('countries'), 'code' => 'NO', 'phonecode' => 47 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 165, 'custom_id'     => getUniqueString('countries'), 'code' => 'OM', 'phonecode' => 968 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 166, 'custom_id'     => getUniqueString('countries'), 'code' => 'PK', 'phonecode' => 92 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 167, 'custom_id'     => getUniqueString('countries'), 'code' => 'PW', 'phonecode' => 680 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 168, 'custom_id'     => getUniqueString('countries'), 'code' => 'PS', 'phonecode' => 970 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 169, 'custom_id'     => getUniqueString('countries'), 'code' => 'PA', 'phonecode' => 507 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 170, 'custom_id'     => getUniqueString('countries'), 'code' => 'PG', 'phonecode' => 675 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 171, 'custom_id'     => getUniqueString('countries'), 'code' => 'PY', 'phonecode' => 595 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 172, 'custom_id'     => getUniqueString('countries'), 'code' => 'PE', 'phonecode' => 51 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 173, 'custom_id'     => getUniqueString('countries'), 'code' => 'PH', 'phonecode' => 63 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 174, 'custom_id'     => getUniqueString('countries'), 'code' => 'PN','phonecode' => 0 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 175, 'custom_id'     => getUniqueString('countries'), 'code' => 'PL', 'phonecode' => 48 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 176, 'custom_id'     => getUniqueString('countries'), 'code' => 'PT', 'phonecode' => 351 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 177, 'custom_id'     => getUniqueString('countries'), 'code' => 'PR', 'phonecode' => 1787 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 178, 'custom_id'     => getUniqueString('countries'), 'code' => 'QA', 'phonecode' => 974 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 179, 'custom_id'     => getUniqueString('countries'), 'code' => 'RE', 'phonecode' => 262 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 180, 'custom_id'     => getUniqueString('countries'), 'code' => 'RO', 'phonecode' => 40 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 181, 'custom_id'     => getUniqueString('countries'), 'code' => 'RU', 'phonecode' => 70 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 182, 'custom_id'     => getUniqueString('countries'), 'code' => 'RW', 'phonecode' => 250 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 183, 'custom_id'     => getUniqueString('countries'), 'code' => 'SH','phonecode' => 290 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 184, 'custom_id'     => getUniqueString('countries'), 'code' => 'KN', 'phonecode' => 1869 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 185, 'custom_id'     => getUniqueString('countries'), 'code' => 'LC', 'phonecode' => 1758 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 186, 'custom_id'     => getUniqueString('countries'), 'code' => 'PM', 'phonecode' => 508 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 187, 'custom_id'     => getUniqueString('countries'), 'code' => 'VC', 'phonecode' => 1784 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 188, 'custom_id'     => getUniqueString('countries'), 'code' => 'WS', 'phonecode' => 684 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 189, 'custom_id'     => getUniqueString('countries'), 'code' => 'SM', 'phonecode' => 378 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 190, 'custom_id'     => getUniqueString('countries'), 'code' => 'ST', 'phonecode' => 239 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 191, 'custom_id'     => getUniqueString('countries'), 'code' => 'SA', 'phonecode' => 966 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 192, 'custom_id'     => getUniqueString('countries'), 'code' => 'SN', 'phonecode' => 221 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 193, 'custom_id'     => getUniqueString('countries'), 'code' => 'RS','phonecode' => 381 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 194, 'custom_id'     => getUniqueString('countries'), 'code' => 'SC', 'phonecode' => 248 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 195, 'custom_id'     => getUniqueString('countries'), 'code' => 'SL', 'phonecode' => 232 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 196, 'custom_id'     => getUniqueString('countries'), 'code' => 'SG', 'phonecode' => 65 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 197, 'custom_id'     => getUniqueString('countries'), 'code' => 'SK', 'phonecode' => 421 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 198, 'custom_id'     => getUniqueString('countries'), 'code' => 'SI', 'phonecode' => 386 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 199, 'custom_id'     => getUniqueString('countries'), 'code' => 'XG', 'phonecode' => 44 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 200, 'custom_id'     => getUniqueString('countries'), 'code' => 'SB', 'phonecode' => 677 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 201, 'custom_id'     => getUniqueString('countries'), 'code' => 'SO', 'phonecode' => 252 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 202, 'custom_id'     => getUniqueString('countries'), 'code' => 'ZA', 'phonecode' => 27 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 203, 'custom_id'     => getUniqueString('countries'), 'code' => 'GS', 'phonecode' => 0 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            // array('id' => 204, 'custom_id'     => getUniqueString('countries'), 'code' => 'SS', 'phonecode' => 211 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 205, 'custom_id'     => getUniqueString('countries'), 'code' => 'ES', 'phonecode' => 34 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 206, 'custom_id'     => getUniqueString('countries'), 'code' => 'LK', 'phonecode' => 94 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 207, 'custom_id'     => getUniqueString('countries'), 'code' => 'SD', 'phonecode' => 249 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 208, 'custom_id'     => getUniqueString('countries'), 'code' => 'SR', 'phonecode' => 597 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 209, 'custom_id'     => getUniqueString('countries'), 'code' => 'SJ', 'phonecode' => 47 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 210, 'custom_id'     => getUniqueString('countries'), 'code' => 'SZ', 'phonecode' => 268 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 211, 'custom_id'     => getUniqueString('countries'), 'code' => 'SE', 'phonecode' => 46 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 212, 'custom_id'     => getUniqueString('countries'), 'code' => 'CH', 'phonecode' => 41 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 213, 'custom_id'     => getUniqueString('countries'), 'code' => 'SY', 'phonecode' => 963 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 214, 'custom_id'     => getUniqueString('countries'), 'code' => 'TW', 'phonecode' => 886 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 215, 'custom_id'     => getUniqueString('countries'), 'code' => 'TJ', 'phonecode' => 992 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 216, 'custom_id'     => getUniqueString('countries'), 'code' => 'TZ', 'phonecode' => 255 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 217, 'custom_id'     => getUniqueString('countries'), 'code' => 'TH', 'phonecode' => 66 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 218, 'custom_id'     => getUniqueString('countries'), 'code' => 'TG', 'phonecode' => 228 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 219, 'custom_id'     => getUniqueString('countries'), 'code' => 'TK', 'phonecode' => 690 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 220, 'custom_id'     => getUniqueString('countries'), 'code' => 'TO', 'phonecode' => 676 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 221, 'custom_id'     => getUniqueString('countries'), 'code' => 'TT', 'phonecode' => 1868 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 222, 'custom_id'     => getUniqueString('countries'), 'code' => 'TN', 'phonecode' => 216 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 223, 'custom_id'     => getUniqueString('countries'), 'code' => 'TR', 'phonecode' => 90 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 224, 'custom_id'     => getUniqueString('countries'), 'code' => 'TM', 'phonecode' => 7370 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 225, 'custom_id'     => getUniqueString('countries'), 'code' => 'TC', 'phonecode' => 1649 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 226, 'custom_id'     => getUniqueString('countries'), 'code' => 'TV', 'phonecode' => 688 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 227, 'custom_id'     => getUniqueString('countries'), 'code' => 'UG', 'phonecode' => 256 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 228, 'custom_id'     => getUniqueString('countries'), 'code' => 'UA', 'phonecode' => 380 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 229, 'custom_id'     => getUniqueString('countries'), 'code' => 'AE', 'phonecode' => 971 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 230, 'custom_id'     => getUniqueString('countries'), 'code' => 'GB', 'phonecode' => 44 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 231, 'custom_id'     => getUniqueString('countries'), 'code' => 'US', 'phonecode' => 1 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 232, 'custom_id'     => getUniqueString('countries'), 'code' => 'UM', 'phonecode' => 1 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 233, 'custom_id'     => getUniqueString('countries'), 'code' => 'UY', 'phonecode' => 598 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 234, 'custom_id'     => getUniqueString('countries'), 'code' => 'UZ', 'phonecode' => 998 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 235, 'custom_id'     => getUniqueString('countries'), 'code' => 'VU', 'phonecode' => 678 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 236, 'custom_id'     => getUniqueString('countries'), 'code' => 'VA', 'phonecode' => 39 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 237, 'custom_id'     => getUniqueString('countries'), 'code' => 'VE', 'phonecode' => 58 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 238, 'custom_id'     => getUniqueString('countries'), 'code' => 'VN', 'phonecode' => 84 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 239, 'custom_id'     => getUniqueString('countries'), 'code' => 'VG', 'phonecode' => 1284 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 240, 'custom_id'     => getUniqueString('countries'), 'code' => 'VI', 'phonecode' => 1340 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 241, 'custom_id'     => getUniqueString('countries'), 'code' => 'WF', 'phonecode' => 681 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 242, 'custom_id'     => getUniqueString('countries'), 'code' => 'EH', 'phonecode' => 212 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 243, 'custom_id'     => getUniqueString('countries'), 'code' => 'YE', 'phonecode' => 967 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 244, 'custom_id'     => getUniqueString('countries'), 'code' => 'YU', 'phonecode' => 38 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 245, 'custom_id'     => getUniqueString('countries'), 'code' => 'ZM', 'phonecode' => 260 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('id' => 246, 'custom_id'     => getUniqueString('countries'), 'code' => 'ZW', 'phonecode' => 263 ,'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
        );
        DB::table('countries')->insert($countries);
    }
}
